"""
Q-Empire Agent Tools — The agent's "hands".
Each tool performs one action in the sandbox environment.
"""

# Lazy import wrapper — prevents failures when optional deps (playwright, etc.) are not installed


def _lazy_import():
    from tools.browser import browser_navigate, browser_search
    from tools.file_system import file_write, file_read, file_edit
    from tools.shell import shell_exec
    from tools.content_gen import generate_content
    from tools.website_builder import generate_website
    from tools.document_gen import generate_document
    from tools.email_sender import send_email
    from tools.crm_tracker import track_crm_entry
    from tools.invoice_generator import create_invoice
    from tools.social_media_poster import generate_social_post
    return {
        "browser_navigate": browser_navigate,
        "browser_search": browser_search,
        "file_write": file_write,
        "file_read": file_read,
        "file_edit": file_edit,
        "shell_exec": shell_exec,
        "generate_content": generate_content,
        "generate_website": generate_website,
        "generate_document": generate_document,
        "deploy_to_github": lambda **kwargs: shell_exec(
            command=f"cd {kwargs['folder']} && git init && git add -A && "
            f"git commit -m 'Auto-generated by Q-Empire Agent' && "
            f"gh repo create {kwargs['repo_name']} --public --source=. --push --remote=origin"
        ),
        "send_email": send_email,
        "track_crm_entry": track_crm_entry,
        "create_invoice": create_invoice,
        "generate_social_post": generate_social_post,
    }


_registry = None


def _get_registry() -> dict:
    global _registry
    if _registry is None:
        _registry = _lazy_import()
    return _registry


# Public alias — TOOL_REGISTRY is populated on first access
class _LazyRegistry(dict):
    def __missing__(self, key):
        return _get_registry()[key]

    def __contains__(self, key):
        return key in _get_registry()

    def keys(self):  # type: ignore[override]
        return _get_registry().keys()

    def items(self):  # type: ignore[override]
        return _get_registry().items()


TOOL_REGISTRY = _LazyRegistry()


def execute_tool(tool_name: str, params: dict) -> str:
    """Execute a registered tool by name with given parameters."""
    if tool_name not in TOOL_REGISTRY:
        raise ValueError(f"Unknown tool: {tool_name}. Available: {list(TOOL_REGISTRY.keys())}")

    tool_fn = TOOL_REGISTRY[tool_name]
    return tool_fn(**params)


def list_tools() -> list[str]:
    """Return list of available tool names."""
    return list(TOOL_REGISTRY.keys())
