"""
Q-Empire Agent Tools — The agent's "hands".
Each tool performs one action in the sandbox environment.
"""
from tools.browser import browser_navigate, browser_search
from tools.file_system import file_write, file_read, file_edit
from tools.shell import shell_exec
from tools.content_gen import generate_content
from tools.website_builder import generate_website
from tools.document_gen import generate_document
from tools.email_sender import send_email

TOOL_REGISTRY = {
    "browser_navigate": browser_navigate,
    "browser_search": browser_search,
    "file_write": file_write,
    "file_read": file_read,
    "file_edit": file_edit,
    "shell_exec": shell_exec,
    "generate_content": generate_content,
    "generate_website": generate_website,
    "generate_document": generate_document,
    "deploy_to_github": lambda **kwargs: shell_exec(
        command=f"cd {kwargs['folder']} && git init && git add -A && "
        f"git commit -m 'Auto-generated by Q-Empire Agent' && "
        f"gh repo create {kwargs['repo_name']} --public --source=. --push --remote=origin"
    ),
    "send_email": send_email,
}


def execute_tool(tool_name: str, params: dict) -> str:
    """Execute a registered tool by name with given parameters."""
    if tool_name not in TOOL_REGISTRY:
        raise ValueError(f"Unknown tool: {tool_name}. Available: {list(TOOL_REGISTRY.keys())}")

    tool_fn = TOOL_REGISTRY[tool_name]
    return tool_fn(**params)


def list_tools() -> list[str]:
    """Return list of available tool names."""
    return list(TOOL_REGISTRY.keys())
