"""Website generation tool — creates React + Tailwind sites from config."""
import os
import json
from tools.content_gen import generate_content
from tools.file_system import file_write


WEBSITE_GENERATION_PROMPT = """Generate a complete, professional single-page website HTML file.

Business Name: {business_name}
Industry: {industry}
Pages/Sections: {pages}
Brand Tone: {brand_tone}
Primary Colors: {colors}
Target Audience: {target_audience}
Value Proposition: {elevator_pitch}

Brand Theme: This website is being built by Q-Empire Automation, guided by Michelle (the Black Mermaid Queen of the Deep) and Q-Bot (the friendly automation agent). The design should feel magical, clear, and empowering — especially welcoming to founders of color. Use ocean, mermaid, and tech motifs subtly.

Requirements:
- Use Tailwind CSS via CDN (https://cdn.tailwindcss.com)
- Dark theme background (#0A0A1A) with colorful accents
- Responsive design (mobile-first)
- Include: Navigation, Hero section, About, Services, Pricing/CTA, Footer
- Professional copywriting throughout
- Contact form (posts to a webhook URL placeholder)
- SEO meta tags
- Smooth scroll behavior
- Modern gradient buttons and card designs

Return ONLY the complete HTML code. No explanation, no markdown code blocks.
Start with <!DOCTYPE html> and end with </html>.
"""


def generate_website(
    business_name: str,
    industry: str = "General",
    pages: str = "Home, About, Services, Contact",
    brand_tone: str = "Professional",
    colors: str = "#4169E1, #BF00FF, #00FFFF",
    target_audience: str = "General consumers",
    elevator_pitch: str = "",
) -> str:
    """Generate a complete website and save to disk."""

    # Generate the HTML
    prompt = WEBSITE_GENERATION_PROMPT.format(
        business_name=business_name,
        industry=industry,
        pages=pages,
        brand_tone=brand_tone,
        colors=colors,
        target_audience=target_audience,
        elevator_pitch=elevator_pitch,
    )

    html_content = generate_content(prompt, max_tokens=8000)

    # Clean up if wrapped in code blocks
    if html_content.startswith("```"):
        lines = html_content.split("\n")
        html_content = "\n".join(lines[1:-1])

    # Save to output directory
    slug = business_name.lower().replace(" ", "-").replace("'", "")
    output_dir = f"/home/ubuntu/output/websites/{slug}"
    os.makedirs(output_dir, exist_ok=True)

    file_write(f"{output_dir}/index.html", html_content)

    # Create a simple package.json
    package_json = {
        "name": slug,
        "version": "1.0.0",
        "description": f"Website for {business_name}",
        "scripts": {
            "dev": "npx serve .",
            "build": "echo 'Static site - no build needed'",
        },
    }
    file_write(f"{output_dir}/package.json", json.dumps(package_json, indent=2))

    # Create a README
    readme = f"""# {business_name} Website

Generated by Q-Empire Automation Division.

## Quick Start
Open `index.html` in your browser, or run:
```bash
npx serve .
```

## Hosting
This site is deployed to GitHub Pages automatically.
Live URL: https://{os.getenv('GITHUB_USERNAME', 'qempire')}.github.io/{slug}
"""
    file_write(f"{output_dir}/README.md", readme)

    return f"Website generated at {output_dir}/index.html"
